myproject/blog/urls.py
from django.urls import path
from .views import home, detail, ArticleDetail, CategoryList, ArticleList, AuthorList, ArticlePreview, SearchList

app_name = 'blog'
urlpatterns = [
    #path('', home, name = 'home'),
    #path('article/<slug:slug>', detail, name = 'detail'),
    path('', ArticleList.as_view(), name = 'index'),
    path('page/<int:page>', ArticleList.as_view(), name = 'index'),
    path('article/<slug:slug>', ArticleDetail.as_view(), name = 'post'),
    path('preview/<int:pk>', ArticlePreview.as_view(), name = 'preview'),
    path('category/<slug:slug>', CategoryList.as_view(), name = 'category'),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name = 'category'),
    path('author/<slug:username>', AuthorList.as_view(), name = 'author'),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name = 'author'),
    path('search/', SearchList.as_view(), name = 'search'),
    path('search/page/<int:page>', SearchList.as_view(), name = 'search'),
]

myproject/config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from account.views import Login, Register, activate

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('comment/', include('comment.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myproject/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from account.models import User
from django.utils.html import format_html
from extensions.utils import jalali_converter
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment


#My managers

class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)

# Create your models here.

class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name="آدرس آی پی")

class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name="children", verbose_name="subscription")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    status = models.BooleanField(default=True, verbose_name="show this?")
    position = models.IntegerField()
    class Meta:
        verbose_name="Category"
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.title
    objects = CategoryManager()

class Article(models.Model):
    STATUS_CHOICES = (
        ("d", "Draft"),
        ("p", "Published"),
        ("i", "investigation"),
        ("b", "back")
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles', verbose_name='author')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    category = models.ManyToManyField(Category, related_name="articles")
    description = models.TextField()
    thumbnail = models.ImageField(upload_to="images")
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    is_special = models.BooleanField(default=False, verbose_name= "مقاله ویژه")
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IPAddress, through="ArticleHit", blank=True, related_name="hits", verbose_name="بازدید ها")

    class Meta:
        verbose_name="Article"

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = 'pulish date'

    def thumbnail_tag(self):
        return format_html("<img width=100 height=70 src='{}' style='border-radius:5px'>".format(self.thumbnail.url))
    thumbnail_tag.short_description = "picture"

    def get_absolute_url(self):
        return reverse("account:home")    
    def category_published(self):
        return self.category.filter(status=True)
    objects = ArticleManager()
    
    def category_to_str(self):
        return ", ".join([category.title for category in self.category.active()])
    category_to_str.short_description = 'category'
    
class ArticleHit(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

myproject/blog/views.py
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from account.models import User
from account.mixins import AuthorAccessMixin
from django.http import HttpResponse
from .models import Article, Category
from django.db.models import Q
# Create your views here.

def home(request):
    articles_list= Article.objects.all()
    paginator = Paginator(articles_list,4)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    context = {"articles" : articles
    }
    return render(request, "blog/home.html", context)

def detail(request, slug):
    context = {
        "article" : Article.objects.get(slug=slug)
    }
    return render(request,'blog/detail.html', context)

# def index(request, page=1):
#     articles_list = Article.objects.all()
#     paginator = Paginator(articles_list, 2)
#     articles = paginator.get_page(page)
#     context = {"articles": articles
#     }
#     return render(request, "blog/article_list.html", context)

class ArticleList(ListView):
    # model = Article
    # template_name = "blog/article_list.html"
    # context_object_name = "articles"
    queryset = Article.objects.published()
    paginate_by = 2



# def post(request, slug):
#     context = {
#         "article" : get_object_or_404(Article.objects.published(), slug=slug, status = "p")
#     }
#     return render(request,'blog/article_detail.html', context)

class ArticleDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        article = get_object_or_404(Article.objects.published(), slug=slug)
        
        ip_address = self.request.user.ip_address
        if ip_address not in article.hits.all():
            article.hits.add(ip_address)
        return article

class ArticlePreview(AuthorAccessMixin, DetailView):
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)

# def category(request, slug, page=1):
#     category = get_object_or_404(Category, slug=slug, status=True)
#     articles_list= category.articles.published()
#     paginator = Paginator(articles_list, 1)
#     articles = paginator.get_page(page)
#     context = {
#         "category": category,
#         "articles": articles,
#     }
#     return render(request, "blog/category.html", context)

class CategoryList(ListView):
    paginate_by = 1
    template_name = "blog/category.html"
    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context
    
class AuthorList(ListView):
    paginate_by = 1
    template_name = "blog/author.html"
    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return author.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context


class SearchList(ListView):
    paginate_by = 1
    template_name = "blog/search_list.html"
    def get_queryset(self):
        search = self.request.GET.get('q')
        return Article.objects.filter(Q(description__icontains=search) | Q(title__icontains=search))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context

myproject/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

myproject/templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load comment_tags %}
{% load base_tags %}
{% load humanize %}
{% block title %} | {{object.title}}{% endblock %}

{% block main %}
<!-- Page Header-->
        <header class="masthead" style="background-image: url('{{object.thumbnail.url}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{{object.title}}</h1>
                            <time>{{object.publish|naturaltime}}</time>
                            {% if article.is_special %}
                                <span class="badge badge-danger" style="font-size: 14px ; color: red;">ویژه</span>
                            {% endif %}
                            <div>بازدیدها: {{ object.hits.count }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    {% popular_articles %}
                    {% hot_articles %}
                    <div class="col-md-10 col-lg-8 col-xl-7 text-justify">
                        {% if object.is_special %}
                            {% if user.is_authenticated and user.is_special_user or object.author == user or user.is_superuser %}
                                {{object.description|safe}}
                            {% else %}
                                {{object.description|striptags|truncatewords:30}}
                                <p class="alert alert-warning">این مقاله ویژه است <a class="alert-link" href="#">تهیه اشتراک</a></p>
                            {% endif %}
                        {% else %}
                            {{object.description|safe}}
                        {% endif %}

                        {% render_comments object request %}
                        {% include_static_jquery %}
                        {% include_bootstrap %}
                    </div>
                </div>
            </div>
        </article>
{% endblock %}

myproject/templates/blog/article_list.html
{% extends 'blog/list.html' %}

{% block header %}{% endblock %}

{% block previous_page_url %}
{% url 'blog:index' page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
{% url 'blog:index' page_obj.next_page_number %}
{% endblock %}

myproject/templates/blog/author.html
{% extends "blog/list.html" %}
{% block header %}<h3 class="alert alert-primary text-center">Author: {{author.get_full_name}}</h3>{% endblock %}


{% block previous_page_url %}
{% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
{% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}

myproject/templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>My project{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href={% static "blog/assets/favicon.ico" %} />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "blog/css/styles.css" %} rel="stylesheet" />
        <link href={% static "blog/css/rtl.css" %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:index' %}">{% title %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                {% category_navbar %}
            </div>
        </nav>

        {% block main %}
		
        {% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "blog/js/scripts.js" %}></script>
    </body>
</html>

myproject/templates/blog/category.html
{% extends "blog/list.html" %}
{% block header %}<h3 class="alert alert-primary text-center">category: {{category.title}}</h3>{% endblock %}


{% block previous_page_url %}
{% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
{% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

myproject/templates/blog/detail.html
<article>
	<img src='{{article.thumbnail.url}}' alt='{{article.title}}' width= 300 height = 220>
	<h1>{{article.title}}</h1>
	<small>{{article.publish}}</small>
	<p>{{article.description}}</p>
</article>

myproject/templates/blog/home.html
<center>
	{% for article in articles %}
		<article>
			<img src='{{article.thumbnail.url}}' alt='{{article.title}}' width= 300 height = 220>
			<h1><a	href="{% url "blog:detail" article.slug %}">{{article.title}}</a></h1>
			<small>{{article.publish}}</small>
			<p>{{article.description}}</p>
		</article>
	{% endfor %}
</center>

myproject/templates/blog/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
{% load base_tags %}
{% load humanize %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static "blog/assets/img/home-bg.jpg" %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>django project</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% block header %}{% endblock %}
                    {% popular_articles %}
                    <br>
                    {% hot_articles %}
                    {% for article in object_list %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url "blog:post" article.slug %}">
                            <h2 class="post-title">
                                {{article.title}}
                                {% if article.is_special %}
                                <span class="badge badge-danger" style="font-size: 14px ; color: red;">ویژه</span>
                                {% endif %}
                            </h2>
                            <h3 class="post-subtitle">{{article.description|striptags|truncatewords:30}}</h3>
                        </a>
                        <p class="post-meta">
                            Posted by:<a href="{% url 'blog:author' article.author %}">{{ article.author.get_full_name }}</a>
                        <p style="direction: ltr;"><small>{{article.publish|naturaltime}}</small></p>
                        </p>
                        <div>
                            {% for cat in article.category_published.all %}
                            <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                            {% endfor %}
                        </div>
                        <div>بازدیدها: {{article.hits.count}}</div>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    {% empty %}
                    <p>محتوایی برای نمایش وجود ندارد.</p>
                    {% endfor %}
                    <!-- Pager-->
                    {% if is_paginated %}
                    {% if page_obj.has_previous %}
                    <div class="d-flex justify-content-end mb-4 pager-botton">
                        <a class="btn btn-primary text-uppercase ml-3" href="{% block previous_page_url %}{% endblock %}">پست های جدید&larr;</a>
                    </div>
                    {% endif %}
                    {% if page_obj.has_next %}
                    <div class="d-flex justify-content-end mb-4 pager-botton">
                        <a class="btn btn-primary text-uppercase ml-3" href="{% block next_page_url %}{% endblock %}">&rarr;پست های قدیمی</a>
                    </div>
                    {% endif %}
            {% endif %}
                </div>
            </div>
        </div>
{% endblock %}

myproject/templates/blog/search_list.html
{% extends "blog/list.html" %}
{% block header %}<h3 class="alert alert-primary text-center">جستجو: {{search}}</h3>{% endblock %}


{% block previous_page_url %}
{% url 'blog:search' page_obj.previous_page_number %}?q={{search}}
{% endblock %}

{% block next_page_url %}
{% url 'blog:search' page_obj.next_page_number %}?q={{search}}
{% endblock %}